FROM node:22-bookworm-slim

WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate

COPY src ./src
COPY tsconfig.json next-env.d.ts ./
ENV NODE_ENV=production
ENV WORKER_HEALTH_PORT=3001
EXPOSE 3001
CMD ["npm", "run", "worker"]
