import Link from "next/link";
import { JsonLd } from "@/components/seo/JsonLd";
import { localizedCopy, SITE_NAME, siteUrl } from "@/lib/seo";
import { seoLocales, seoAirports, intercityRoutes, fleetPages, type SeoLocale } from "@/lib/site-content";

export function generateStaticParams() { return seoLocales.map(lang => ({ lang })); }

export default async function SeoHomePage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params; const locale = seoLocales.includes(lang as SeoLocale) ? lang as SeoLocale : "en"; const copy = localizedCopy(locale);
  return <main className="ev-page ev-page--wide"><JsonLd value={{ "@context": "https://schema.org", "@type": "WebSite", name: SITE_NAME, url: `${siteUrl()}/${locale}` }} /><div className="ev-eyebrow">Eurasian VIP Transfer</div><h1 className="ev-h1">{copy.home}</h1><p className="ev-muted" style={{ maxWidth: 760 }}>{copy.lead}</p><div className="ev-actions" style={{ marginTop: 20 }}><Link className="ev-btn" href={`/rezervasyon?lang=${locale}`}>{copy.book} ↗</Link><Link className="ev-btn ev-btn--ghost" href={`/${locale}/havalimani-transferi`}>{copy.airports}</Link></div><section className="ev-grid ev-grid--3" style={{ marginTop: 32 }}>{[{ href: `/${locale}/havalimani-transferi`, title: copy.airports, count: `${seoAirports.length}+` }, { href: `/${locale}/sehirlerarasi-transfer`, title: copy.routes, count: `${intercityRoutes.length}` }, { href: `/${locale}/filomuz`, title: copy.fleet, count: `${fleetPages.length}` }].map(card => <Link className="ev-card ev-link-card" href={card.href} key={card.href}><div className="ev-eyebrow">{card.count}</div><h2 style={{ margin: "8px 0" }}>{card.title}</h2><span className="ev-muted">{copy.explore} →</span></Link>)}</section><section className="ev-grid ev-grid--3" style={{ marginTop: 16 }}><Link className="ev-card ev-link-card" href={`/${locale}/medikal-transfer`}><h2>{copy.medical}</h2><p className="ev-muted">Hastane, klinik ve otel arasında planlı transfer.</p></Link><Link className="ev-card ev-link-card" href={`/${locale}/kurumsal`}><h2>{copy.corporate}</h2><p className="ev-muted">Saatlik ve günlük profesyonel şoför hizmeti.</p></Link><Link className="ev-card ev-link-card" href={`/${locale}/iletisim`}><h2>{copy.contact}</h2><p className="ev-muted">Rezervasyon ekibimizle iletişime geçin.</p></Link></section></main>;
}
