"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { seoAirports } from "@/lib/site-content";

export function HeroBookingWidget() {
  const [pickup, setPickup] = useState("IST"); const [dropoff, setDropoff] = useState("AYT"); const [date, setDate] = useState(""); const [time, setTime] = useState("12:00"); const [passengers, setPassengers] = useState("2"); const [luggage, setLuggage] = useState("2"); const [roundTrip, setRoundTrip] = useState(false); const [currency, setCurrency] = useState("EUR");
  const query = useMemo(() => new URLSearchParams({ airport: pickup, destination: seoAirports.find(item => item.code === dropoff)?.city || dropoff, date, time, passengers, luggage, roundTrip: String(roundTrip), currency }).toString(), [currency, date, dropoff, luggage, passengers, pickup, roundTrip, time]);
  return <section className="ev-card" aria-label="VIP transfer price calculator"><div className="ev-eyebrow">Instant route quote</div><h2 style={{ margin: "8px 0 18px" }}>Plan your Turkey transfer</h2><div className="ev-field-grid"><label className="ev-field"><span className="ev-label">Pickup</span><select className="ev-select" value={pickup} onChange={e => setPickup(e.target.value)}>{seoAirports.map(item => <option key={item.code} value={item.code}>{item.name} ({item.code})</option>)}</select></label><label className="ev-field"><span className="ev-label">Drop-off</span><select className="ev-select" value={dropoff} onChange={e => setDropoff(e.target.value)}>{seoAirports.map(item => <option key={item.code} value={item.code}>{item.city}</option>)}</select></label><label className="ev-field"><span className="ev-label">Date</span><input className="ev-input" type="date" value={date} onChange={e => setDate(e.target.value)} required /></label><label className="ev-field"><span className="ev-label">Time</span><input className="ev-input" type="time" value={time} onChange={e => setTime(e.target.value)} required /></label><label className="ev-field"><span className="ev-label">Passengers</span><input className="ev-input" type="number" min="1" max="16" value={passengers} onChange={e => setPassengers(e.target.value)} /></label><label className="ev-field"><span className="ev-label">Luggage</span><input className="ev-input" type="number" min="0" max="30" value={luggage} onChange={e => setLuggage(e.target.value)} /></label><label className="ev-field"><span className="ev-label">Currency</span><select className="ev-select" value={currency} onChange={e => setCurrency(e.target.value)}><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option><option>RUB</option></select></label></div><label className="ev-choice" style={{ margin: "14px 0" }}><input type="checkbox" checked={roundTrip} onChange={e => setRoundTrip(e.target.checked)} /> Round trip <span className="ev-badge ev-badge--teal">10% discount</span></label><Link className="ev-btn" href={`/rezervasyon?${query}`}>See instant price →</Link></section>;
}
