"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Application = { id: string; applicationNo: string; fullName: string; phone: string; email: string | null; experienceYears: number | null; languages: string[]; imageUrls: string[]; notes: string | null; status: string; createdAt: string; whatsappMessage: string | null };

export function GreeterApplicationsPanel({ applications }: { applications: Application[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [messages, setMessages] = useState<Record<string, string>>({});
  async function decide(id: string, action: "approve" | "reject") { setBusy(id); try { const rejectionReason = action === "reject" ? window.prompt("Red nedeni") || "Başvuru kriterleri karşılanmadı." : undefined; const res = await fetch(`/api/greeter-applications/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, rejectionReason }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); if (body.application.whatsappMessage) setMessages(current => ({ ...current, [id]: body.application.whatsappMessage })); router.refresh(); } catch (e) { alert((e as Error).message); } finally { setBusy(null); } }
  const pending = applications.filter(item => item.status === "PENDING");
  return <section id="karsilamaci-basvurulari" className="ev-card" style={{ marginTop: 24 }}><div className="ev-card-row"><div><div className="ev-eyebrow">İnsan kaynağı</div><h2 style={{ margin: "6px 0" }}>Karşılamacı başvuruları</h2></div><span className="ev-badge ev-badge--gold">{pending.length} onay bekliyor</span></div>{applications.length === 0 && <div className="ev-empty">Henüz başvuru yok.</div>}<div className="ev-stack" style={{ marginTop: 14 }}>{applications.map(application => <article className="ev-card" key={application.id} style={{ background: "rgba(14,42,52,.35)" }}><div className="ev-card-row"><div><strong>{application.fullName}</strong><div className="ev-muted">{application.applicationNo} · {application.phone}</div></div><span className={`ev-badge ${application.status === "PENDING" ? "ev-badge--gold" : application.status === "APPROVED" ? "ev-badge--teal" : "ev-badge--rose"}`}>{application.status === "PENDING" ? "Onay bekliyor" : application.status === "APPROVED" ? "Onaylandı" : "Reddedildi"}</span></div><div className="ev-field-grid" style={{ marginTop: 12 }}><div><small className="ev-muted">Deneyim</small><div>{application.experienceYears ?? "Belirtilmemiş"} yıl</div></div><div><small className="ev-muted">Diller</small><div>{application.languages.join(", ") || "Belirtilmemiş"}</div></div><div><small className="ev-muted">Başvuru</small><div>{new Date(application.createdAt).toLocaleString("tr-TR")}</div></div></div>{application.notes && <p className="ev-muted">Not: {application.notes}</p>}{application.imageUrls.length > 0 && <div className="ev-card-row" style={{ justifyContent: "flex-start", flexWrap: "wrap" }}>{application.imageUrls.map((src, index) => <img key={src.slice(-20) + index} src={src} alt={`Fotoğraf ${index + 1}`} style={{ width: 110, height: 76, objectFit: "cover", borderRadius: 8 }} />)}</div>}{application.status === "PENDING" && <div className="ev-actions" style={{ marginTop: 12 }}><button className="ev-btn" disabled={busy === application.id} onClick={() => decide(application.id, "approve")}>{busy === application.id ? "İşleniyor…" : "Onayla ve hesap oluştur"}</button><button className="ev-btn ev-btn--ghost" disabled={busy === application.id} onClick={() => decide(application.id, "reject")}>Reddet</button></div>}{(application.whatsappMessage || messages[application.id]) && <div className="ev-stack" style={{ marginTop: 12 }}><label className="ev-label">WhatsApp mesajı — manuel gönderim</label><textarea className="ev-input" rows={7} readOnly value={messages[application.id] || application.whatsappMessage || ""} /><button className="ev-btn ev-btn--ghost" onClick={() => navigator.clipboard.writeText(messages[application.id] || application.whatsappMessage || "")}>Mesajı kopyala</button></div>}</article>)}</div></section>;
}
