"use client";

import { useState } from "react";

type Staff = { id: string; name: string; role: string };
export default function RatePage() {
  const [code, setCode] = useState(""); const [phone, setPhone] = useState(""); const [staff, setStaff] = useState<Staff[]>([]); const [scores, setScores] = useState<Record<string, number>>({}); const [comment, setComment] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function find(event: React.FormEvent) { event.preventDefault(); setError(""); const response = await fetch(`/api/ratings?code=${encodeURIComponent(code)}&phone=${encodeURIComponent(phone)}`, { method: "PUT" }); const body = await response.json(); if (!response.ok) { setError(body.error); return; } setStaff(body.booking.staff); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); for (const person of staff) { const response = await fetch("/api/ratings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bookingId: code, guestPhone: phone, subjectUserId: person.id, score: scores[person.id], comment, raterName: "Misafir" }) }); if (!response.ok) { const body = await response.json(); setError(body.error); return; } } setMessage("Değerlendirmeniz alındı, teşekkür ederiz."); }
  return <main className="ev-page" style={{ maxWidth: 680 }}><div className="ev-eyebrow">Hizmet değerlendirmesi</div><h1 className="ev-h1">Ekibimizi puanlayın</h1>{staff.length === 0 ? <form className="ev-card ev-stack" onSubmit={find}><label className="ev-field"><span className="ev-label">Rezervasyon kodu</span><input className="ev-input" required value={code} onChange={e => setCode(e.target.value)} placeholder="EVT-1001" /></label><label className="ev-field"><span className="ev-label">Rezervasyondaki telefon</span><input className="ev-input" required value={phone} onChange={e => setPhone(e.target.value)} /></label><button className="ev-btn">Ekibi getir</button>{error && <div className="ev-alert ev-alert--error">{error}</div>}</form> : <form className="ev-card ev-stack" onSubmit={submit}>{staff.map(person => <label className="ev-field" key={person.id}><span className="ev-label">{person.name} · {person.role === "DRIVER" ? "Şoför" : "Karşılamacı"}</span><select className="ev-select" required value={scores[person.id] || ""} onChange={e => setScores(current => ({ ...current, [person.id]: Number(e.target.value) }))}><option value="">Puan seçin</option>{[5, 4, 3, 2, 1].map(score => <option key={score} value={score}>{"★".repeat(score)} ({score}/5)</option>)}</select></label>)}<label className="ev-field"><span className="ev-label">Yorum (opsiyonel)</span><textarea className="ev-input" rows={4} value={comment} onChange={e => setComment(e.target.value)} /></label><button className="ev-btn">Değerlendirmeyi gönder</button>{error && <div className="ev-alert ev-alert--error">{error}</div>}</form>}{message && <div className="ev-card" style={{ marginTop: 16 }}><strong>{message}</strong></div>}</main>;
}
